### ISSUE TITLE
这几天一直无法获取小心心

### ISSUE THREAD

**Issue by DEabcdp** [andywang425/BLTH#247]
### 描述bug

无法【自动获取小心心】。右上角出现了获取的提示，但是等了一天包裹里也没有。

### 重现bug

1.进入直播间。
2.开启自动获取小心心，点击再次执行所有任务。

### 预期行为

过几分钟能够获取小心心。

### 截图

![image](https://user-images.githubusercontent.com/62452364/166458662-1c41a2a6-0b44-4b5c-995d-d1bb62679448.png)

### 运行日志

invalid/:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_FAILED
875.js:2 [Intervention]Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: chrome-extension://emffkefkbkpkgpdeeooapgaicgmcbolj/fonts/OpenSans-Regular.woff2
data.bilibili.com/gol/postweb:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
sentry-5.2.1.min.js:2 fMp4Player v1.39
sentry-5.2.1.min.js:2 Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2022 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence #
sentry-5.2.1.min.js:2 Version: V4.0.0 "Life Experience", CodeName: Neptune.
sentry-5.2.1.min.js:2 Chrome verion: 101
sentry-5.2.1.min.js:2 seek to: 3695.692/7415.332s, pos=683806185
s1.hdslb.com/bfs/seed/blive/blfe-link-shortassets/dist/component.statistics/log-reporter.js:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
sentry-5.2.1.min.js:2 
        
       统计脚本加载失败： Error: Could not load URL at //s1.hdslb.com/bfs/seed/blive/blfe-link-shortassets/dist/component.statistics/log-reporter.js
    at HTMLScriptElement.i.onerror (bilibili.dca0807fead7df2ab857.js:2:278348)
(匿名) @ sentry-5.2.1.min.js:2
invalid/:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_FAILED
54:1 
        
       Uncaught (in promise) Error: Could not load URL at //s1.hdslb.com/bfs/seed/blive/blfe-link-shortassets/dist/component.statistics/log-reporter.js
    at HTMLScriptElement.i.onerror (bilibili.dca0807fead7df2ab857.js:2:278348)
data.bilibili.com/gol/postweb:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3568 
        
      
        
        
      
        
      
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at RoomHeart.e (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3568:29)
    at RoomHeart.getInfoByRoom (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3532:20)
    at async RoomHeart.start (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3521:20)
    at async run (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3697:15)
live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3568 
        
      
        
        
      
        
      
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at RoomHeart.e (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3568:29)
    at RoomHeart.getInfoByRoom (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3532:20)
    at async RoomHeart.start (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3521:20)
    at async run (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3697:15)
live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3568 
        
      
        
        
      
        
      
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at RoomHeart.e (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3568:29)
    at RoomHeart.getInfoByRoom (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3532:20)
    at async RoomHeart.start (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3521:20)
    at async run (userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3697:15)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3568 

 ......

DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/room-player.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

### 操作系统

Windows 10

### 浏览器

Microsoft Edge 版本 101.0.1210.32 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey 4.16

### 挂机助手版本

5.8

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by 594854527** [comment]
edge和chrome浏览器开无痕模式之后可以正常获取小心心

**Comment by DEabcdp** [comment]
> edge和chrome浏览器开无痕模式之后可以正常获取小心心

还是不行

**Comment by andywang425** [comment]
看上去像是心跳请求被浏览器拓展拦截了。有使用广告拦截拓展吗？

**Comment by DEabcdp** [comment]
> 看上去像是心跳请求被浏览器拓展拦截了。有使用广告拦截拓展吗？

用了adblock，关了之后果然能获取了，感谢！！

**Comment by andywang425** [comment]
如果知道怎么设置adblock白名单的话把心跳的地址填加到白名单中即可，不用关闭拓展
![image](https://user-images.githubusercontent.com/56548456/166670725-d9ffba04-f176-4af9-a6b9-65bc99e7d5d1.png)

我想大概是这么写（很久没用adblock了，不清楚具体语法）
https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/*

**Comment by DEabcdp** [comment]
> 如果知道怎么设置adblock白名单的话把心跳的地址填加到白名单中即可，不用关闭拓展 ![image](https://user-images.githubusercontent.com/56548456/166670725-d9ffba04-f176-4af9-a6b9-65bc99e7d5d1.png)
> 
> 我想大概是这么写（很久没用adblock了，不清楚具体语法） https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/*

我想应该是@@||live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/*
@@||live-trace.bilibili.com/xlive/rdata-interface/v1/heartbeat/*
还有第二条。
